server:
  port: 80

spring:
  application:
    name: cloud-order-com.atgugu.springcloud.service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1

eureka:
  client:
    #    表示不向注册中心注册自己
    register-with-eureka: true
    #    表示自己就是注册中心，只需要维护实例不需要检索服务
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:7002/eureka/,http://localhost:7001/eureka/