server:
  port: 80

spring:
  application:
    name: cloud-order-feign-com.atgugu.springcloud.service

eureka:
  client:
    #表示不注册上去
    register-with-eureka: false
    # 遇到的坑 除了eureka本身（因为是服务端，不需要检索服务）
    # 但是如果作为eureka的客户端，无论你是消费者还是提供者的模块，都要设置为true（其实默认也是true的）
    # 如果是消费者的话是无法调用注册eureka的模块的
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:7002/eureka/,http://localhost:7001/eureka/

feign:
  client:
    config: # 设置请求超时时间和连接超时时间 注意这个default应该是个Map集合，所以没提示，注意别写错了
      default:
        ConnectTimeout: 5000
        ReadTimeout: 5000

#配置日志级别:
logging:
  level:
    com.atgugu.springcloud.service.PaymentFeignService: debug
