eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:7002/eureka/,http://localhost:7001/eureka/
  instance:
    #    实例名
    instance-id: cloud-config-client3366
    #    是否显示IP地址
    prefer-ip-address: true