server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #discovery.locator.enabled=true是用来开启注册中心找服务名实现动态转发的
      routes:
#        - id: payment_routh #payment_route
#          uri: http://localhost:8001     #访问localhost:9527/payment/get/3 如果有这个请求地址，断言成功，可以访问
#          predicates:
#            - Path=/payment/get/**  #断言 路径相匹配的进行路由
#        - id: payment_routh2
#          uri: http://localhost:8001
#          predicates:
#            - Path=/payment/timeout/**
        #------------------------------------如果是提供者集群，需要用到动态路由实现负载均衡，就是下面的方法
        #uri前的lb:是固定的代表负载均衡，后面就是微服务的应用名，predicates与上面不变，访问http://localhost:9527/payment/timeout
        #就会根据负载均衡规则请求到对应集群中的其中一个服务器
        - id: payment_routeDt #随便取
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/timeout/**
            - Cookie=C-ookie,rhine  #有C-ookie这个cookie且这个cookie要满足后面的这个正则表达式规则
eureka:
  client:
    #    表示不向注册中心注册自己
    register-with-eureka: true
    #    表示自己就是注册中心，只需要维护实例不需要检索服务
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:7002/eureka/,http://localhost:7001/eureka/
  instance:
    #    实例名
    instance-id: cloud-gateway-9527
    #    是否显示IP地址
    prefer-ip-address: true