server:
  port: 2003
spring:
  application:
    name: seata-account-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Iccl19950314
    url: jdbc:mysql://124.71.238.184:3306/seata_account?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT
  cloud:
    nacos:
      discovery:
        #        server-addr: 127.0.0.1:8848
        server-addr: 124.71.238.184:8848  #华为云
    alibaba:
      seata:
        tx-service-group: my_tx_group
management:
  endpoints:
    web:
      exposure:
        include: "*"
mybatis:
  type-aliases-package: com.atgugu.springcloud.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



