server:
  port: 8001

spring:
  application:
    name: cloud-hystrix-payment-com.atgugu.springcloud.service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT

mybatis:
  type-aliases-package: com.atgugu.springcloud.entities
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

eureka:
  client:
    #    表示不向注册中心注册自己
    register-with-eureka: true
    #    表示自己就是注册中心，只需要维护实例不需要检索服务
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:7002/eureka/,http://localhost:7001/eureka/
  instance:
    #    实例名
    instance-id: payment-hystrix-8001
    #    是否显示IP地址
    prefer-ip-address: true