server:
  port: 80

spring:
  application:
    name: cloud-feign-hystrix-order-com.atgugu.springcloud.service

eureka:
  client:
    #    表示不向注册中心注册自己
    register-with-eureka: true
    #    表示自己就是注册中心，只需要维护实例不需要检索服务
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:7002/eureka/,http://localhost:7001/eureka/
feign:
  circuitbreaker:
    enabled: true
